version: "3.4"

services:
  src:
    image: ${IMAGE_VERTION}.${BUILD_NUMBER}
    volumes:
      - web-content:/app
    networks:
      - frontend

  web${CURR_NUM}:
    restart: unless-stopped
    image: mcr.microsoft.com/dotnet/core/aspnet:${RUNTIME_VERSION}
    container_name: web_${CURR_NUM}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - web-content:/app
    networks:
      - frontend
    ports:
      - "808${CURR_NUM}:80"
    working_dir: /app
    command: dotnet webapp.dll
    depends_on:
      - "src"
volumes:
  web-content:
networks:
  frontend:
    external:
      name: frontend
