version: "3.4"

services:
  src:
    image: ${DOCKER_REGISTRY}${IMAGE_VERTION}.${BUILD_NUMBER}
    volumes:
      - web-content:/app
    networks:
      - frontend

  web0:
    restart: unless-stopped
    image: mcr.microsoft.com/dotnet/core/aspnet:${RUNTIME_VERSION}
    container_name: web_0
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - web-content:/app
    networks:
      - frontend
    ports:
      - "8080:80"
    working_dir: /app
    command: dotnet webapp.dll
    depends_on:
      - "src"
  web1:
    restart: unless-stopped
    image: mcr.microsoft.com/dotnet/core/aspnet:${RUNTIME_VERSION}
    container_name: web_1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - web-content:/app
    networks:
      - frontend
    ports:
      - "8081:80"
    working_dir: /app
    command: dotnet webapp.dll
    depends_on:
      - "src"
volumes:
  web-content:
networks:
  frontend:
    external:
      name: frontend
